# ==============================================================================
# 05_figure2_treg_frequency_bins.R
# ==============================================================================
# Goal:
#   Create the Treg repertoire frequency-bin stacked bar plot using the saved
#   frequency-bin summary table.
#
# Input:
#   results/intermediate/bulk_treg_frequency_bin_summary.csv
#
# Outputs:
#   results/figures/figure2_treg_frequency_bins.png
#   results/figures/figure2_treg_frequency_bins.pdf
#
# Notes:
#   This script uses the processed frequency-bin summary generated by:
#     04_calculate_bulk_treg_clonotype_frequencies.R
#
#   The plot shows the percentage of each Treg repertoire represented by
#   clonotypes in predefined frequency bins.
# ==============================================================================


# ------------------------------------------------------------------------------
# 0. Load packages
# ------------------------------------------------------------------------------

library(dplyr)
library(ggplot2)
library(readr)
library(scales)


# ------------------------------------------------------------------------------
# 1. Define input and output paths
# ------------------------------------------------------------------------------

input_path <- file.path(
  "results",
  "intermediate",
  "bulk_treg_frequency_bin_summary.csv"
)

figure_dir <- file.path("results", "figures")

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)


# ------------------------------------------------------------------------------
# 2. Load frequency-bin summary table
# ------------------------------------------------------------------------------

bin_summary_treg <- read_csv(input_path, show_col_types = FALSE)


# ------------------------------------------------------------------------------
# 3. Check columns needed for plotting
# ------------------------------------------------------------------------------

required_cols <- c(
  "sample_id",
  "mouse",
  "cell_subset",
  "injection",
  "frequency_bin",
  "total_frequency_percent"
)

missing_cols <- setdiff(required_cols, colnames(bin_summary_treg))

if (length(missing_cols) > 0) {
  stop(
    "Missing columns needed for this script: ",
    paste(missing_cols, collapse = ", ")
  )
}


# ------------------------------------------------------------------------------
# 4. Define Treg sample order
# ------------------------------------------------------------------------------

sample_order <- c(
  "L578T38_trimmed-prod",
  "L578T40_trimmed-prod",
  "L578T22_trimmed-prod",
  "L575T17_trimmed-prod",
  "L578T26_trimmed-prod",
  "L575T20_trimmed-prod",
  "L578T34_trimmed-prod",
  "L575T16_trimmed-prod",
  "L578T42_trimmed-prod",
  "L578T23_trimmed-prod",
  "L578T36_trimmed-prod",
  "L578T27_trimmed-prod",
  "L578T30_trimmed-prod",
  "L575T18_trimmed-prod"
)


# ------------------------------------------------------------------------------
# 5. Define frequency-bin order and colours
# ------------------------------------------------------------------------------

bin_levels <- c(
  "]0.01,1]",
  "]0.001,0.01]",
  "]0.0001,0.001]",
  "]0.00001,0.0001]",
  "]0.000001,0.00001]"
)

bin_colors <- c(
  "]0.000001,0.00001]" = "#003f5c",
  "]0.00001,0.0001]" = "#58508d",
  "]0.0001,0.001]" = "#bc5090",
  "]0.001,0.01]" = "#ff6361",
  "]0.01,1]" = "#ffa600"
)


# ------------------------------------------------------------------------------
# 6. Prepare plotting table
# ------------------------------------------------------------------------------

plot_data <- bin_summary_treg %>%
  filter(cell_subset == "Treg") %>%
  mutate(
    sample_id = factor(sample_id, levels = sample_order),
    frequency_bin = factor(frequency_bin, levels = bin_levels),
    mouse = as.character(mouse),
    injection = as.character(injection)
  ) %>%
  filter(!is.na(sample_id)) %>%
  droplevels()

if (nrow(plot_data) == 0) {
  stop("No Treg rows remained after filtering and applying sample_order.")
}


# ------------------------------------------------------------------------------
# 7. Check sample order
# ------------------------------------------------------------------------------

samples_in_data <- sort(unique(bin_summary_treg$sample_id))
samples_not_in_order <- setdiff(samples_in_data, sample_order)
samples_order_not_in_data <- setdiff(sample_order, samples_in_data)

if (length(samples_not_in_order) > 0) {
  warning(
    "These samples are in the input data but not in sample_order: ",
    paste(samples_not_in_order, collapse = ", ")
  )
}

if (length(samples_order_not_in_data) > 0) {
  warning(
    "These samples are in sample_order but not in the input data: ",
    paste(samples_order_not_in_data, collapse = ", ")
  )
}


# ------------------------------------------------------------------------------
# 8. Set mouse facet order based on sample order
# ------------------------------------------------------------------------------

mouse_order <- plot_data %>%
  distinct(sample_id, mouse) %>%
  arrange(sample_id) %>%
  pull(mouse) %>%
  unique()

plot_data <- plot_data %>%
  mutate(
    mouse = factor(mouse, levels = mouse_order)
  )


# ------------------------------------------------------------------------------
# 9. Create stacked frequency-bin plot
# ------------------------------------------------------------------------------

p_frequency_bins <- ggplot(
  plot_data,
  aes(
    x = sample_id,
    y = total_frequency_percent,
    fill = frequency_bin
  )
) +
  geom_col(width = 0.8) +
  facet_wrap(
    ~ mouse,
    scales = "free_x",
    nrow = 1
  ) +
  scale_fill_manual(
    values = bin_colors,
    breaks = bin_levels,
    drop = FALSE
  ) +
  scale_y_continuous(
    labels = label_percent(scale = 1),
    expand = expansion(mult = c(0, 0.02))
  ) +
  labs(
    title = "Distribution of clonotype abundance across Treg repertoires",
    x = "Sample",
    y = "Percentage of repertoire",
    fill = "Frequency bin"
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12),
    plot.title = element_text(size = 13, face = "bold"),
    strip.text = element_text(size = 10, face = "bold"),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9)
  )


# ------------------------------------------------------------------------------
# 10. Save figure
# ------------------------------------------------------------------------------

ggsave(
  filename = file.path(figure_dir, "figure2_treg_frequency_bins.png"),
  plot = p_frequency_bins,
  width = 10,
  height = 5,
  dpi = 300
)

ggsave(
  filename = file.path(figure_dir, "figure2_treg_frequency_bins.pdf"),
  plot = p_frequency_bins,
  width = 10,
  height = 5
)


# ------------------------------------------------------------------------------
# 11. Print quick checks
# ------------------------------------------------------------------------------

message("Figure 2 frequency-bin plot complete.")
message("Figures saved to: ", figure_dir)
message("Number of Treg samples plotted: ", n_distinct(plot_data$sample_id))

message("Frequency-bin totals per sample:")
print(
  plot_data %>%
    group_by(sample_id, mouse) %>%
    summarise(
      total_percent = sum(total_frequency_percent, na.rm = TRUE),
      .groups = "drop"
    )
)